type Query {
  # Identity
  jsonIdentity(x: JSON!): JSON!
  jsonIdentityOpt(x: JSON): JSON

  # NONULL coercion
  jsonCoerceFromOpt(x: JSON): JSON!
  jsonCoerceToOpt(x: JSON!): JSON

  # String de/serialization
  jsonParse(x: String!): JSON!
  jsonToString(x: JSON!): String!

  # Lists
  jsonListUnion(a: [JSON!]!, b: [JSON!]!): [JSON!]!
  jsonListConcat(a: [JSON!]!, b: [JSON!]!): [JSON!]!
  jsonListReverse(x: [JSON!]!): [JSON!]!
  jsonListUnique(x: [JSON!]!): [JSON!]!
  jsonListFilterNulls(x: [JSON]): [JSON!]!

  # Operations
}
