type Query {
  # Identity
  idIdentity(x: ID!): ID!
  idIdentityOpt(x: ID): ID

  # NONULL coercion
  idCoerceFromOpt(x: ID): ID!
  idCoerceToOpt(x: ID!): ID

  # String de/serialization
  idParse(x: String!): ID!
  idToString(x: ID!): String!

  # Lists
  idListUnion(a: [ID!]!, b: [ID!]!): [ID!]!
  idListConcat(a: [ID!]!, b: [ID!]!): [ID!]!
  idListReverse(x: [ID!]!): [ID!]!
  idListUnique(x: [ID!]!): [ID!]!
  idListFilterNulls(x: [ID]): [ID!]!

  # Operations
}
