type Query {
  # Identity
  floatIdentity(x: Float!): Float!
  floatIdentityOpt(x: Float): Float

  # NONULL coercion
  floatCoerceFromOpt(x: Float): Float!
  floatCoerceToOpt(x: Float!): Float

  # String de/serialization
  floatParse(x: String!): Float!
  floatToString(x: Float!): String!

  # Lists
  floatListUnion(a: [Float!]!, b: [Float!]!): [Float!]!
  floatListConcat(a: [Float!]!, b: [Float!]!): [Float!]!
  floatListReverse(x: [Float!]!): [Float!]!
  floatListUnique(x: [Float!]!): [Float!]!
  floatListFilterNulls(x: [Float]): [Float!]!

  # Operations
  floatEqual(a: Float!, b: Float!): Boolean!
  floatGreaterThan(x: Float!, min: Float!): Boolean!
  floatLessThan(x: Float!, max: Float!): Boolean!
}
