type Query {
  # Identity
  booleanIdentity(x: Boolean!): Boolean!
  booleanIdentityOpt(x: Boolean): Boolean

  # NONULL coercion
  booleanCoerceFromOpt(x: Boolean): Boolean!
  booleanCoerceToOpt(x: Boolean!): Boolean

  # String de/serialization
  booleanParse(x: String!): Boolean!
  booleanToString(x: Boolean!): String!

  # Lists
  booleanListUnion(a: [Boolean!]!, b: [Boolean!]!): [Boolean!]!
  booleanListConcat(a: [Boolean!]!, b: [Boolean!]!): [Boolean!]!
  booleanListReverse(x: [Boolean!]!): [Boolean!]!
  booleanListUnique(x: [Boolean!]!): [Boolean!]!
  booleanListFilterNulls(x: [Boolean]): [Boolean!]!

  # Operations
  booleanOr(a: Boolean!, b: Boolean!): Boolean!
  booleanAnd(a: Boolean!, b: Boolean!): Boolean!
  booleanXor(a: Boolean!, b: Boolean!): Boolean!
  booleanNot(x: Boolean!): Boolean!
}
