type Query {
  # Identity
  stringIdentity(x: String!): String!
  stringIdentityOpt(x: String): String

  # NONULL coercion
  stringCoerceFromOpt(x: String): String!
  stringCoerceToOpt(x: String!): String

  # Lists
  stringListUnion(a: [String!]!, b: [String!]!): [String!]!
  stringListConcat(a: [String!]!, b: [String!]!): [String!]!
  stringListReverse(x: [String!]!): [String!]!
  stringListUnique(x: [String!]!): [String!]!
  stringListFilterNulls(x: [String]): [String!]!
  stringListHead(x: [String!]!): String
  stringListWrap(x: String!): [String!]!

  # Operations
  stringLength(x: String!): Int!
  stringReverse(x: String!): String!
  stringConcat(a: String!, b: String!): String!
  stringEqual(a: String!, b: String!): String!
  stringReplace(source: String!, search: String!, replace: String!): String!
}
