type Query {
  # Identity
  timeIdentity(a: Time!): Time!
  timeIdentityOpt(a: Time): Time

  # NONULL coercion
  timeCoerceFromOpt(a: Time): Time!
  timeCoerceToOpt(a: Time!): Time

  # String de/serialization
  timeParse(string: String!): Time!
  timeToString(a: Time!): String!

  # Lists
  timeListUnion(a: [Time!]!, b: [Time!]!): [Time!]!
  timeListConcat(a: [Time!]!, b: [Time!]!): [Time!]!
  timeListReverse(a: [Time!]!): [Time!]!

  # Operations
  timeNow: Time!
}
