scalar Date
scalar DateTime
scalar Time
scalar JSON

type Info {
  id: ID!
  version: String!
  name: String!
  description: String
}

type Query {
  """
  Mandatory service manifest.
  """
  info: Info!
}
